-- ============================================
-- INTERACTIVE JSON DATABASE SETUP
-- ============================================

USE ROLE ACCOUNTADMIN;

-- Create the new database
CREATE DATABASE IF NOT EXISTS INTERACTIVE_JSON_DB;
USE DATABASE INTERACTIVE_JSON_DB;

-- Create schema
CREATE SCHEMA IF NOT EXISTS STREAMING;
USE SCHEMA STREAMING;

-- Create the Interactive Table for Customers
CREATE OR REPLACE INTERACTIVE TABLE CUSTOMERS CLUSTER BY (CLIENTIP) (
    EVENTDATE DATE,
    COUNTERID NUMBER(38,0),
    CLIENTIP VARCHAR(16777216),
    SEARCHENGINEID NUMBER(38,0),
    SEARCHPHRASE VARCHAR(16777216),
    RESOLUTIONWIDTH NUMBER(38,0),
    TITLE VARCHAR(16777216),
    ISREFRESH NUMBER(38,0),
    DONTCOUNTHITS NUMBER(38,0)
);

-- Create a stage for JSON files
CREATE OR REPLACE STAGE JSON_STAGE
    DIRECTORY = (ENABLE = TRUE)
    FILE_FORMAT = (TYPE = 'JSON');

-- Create file format for JSON ingestion
CREATE OR REPLACE FILE FORMAT JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = TRUE
    IGNORE_UTF8_ERRORS = TRUE;

-- Verify table created
DESCRIBE TABLE CUSTOMERS;
