-- SHOW INGESTION LOGS OF SNOWPIPE STREAMING V2
SHOW PIPES IN SCHEMA INTERACTIVE_JSON_DB.STREAMING;

SELECT 
    COUNT(*) AS TOTAL_RECORDS,
    MIN(EVENTDATE) AS EARLIEST_EVENT,
    MAX(EVENTDATE) AS LATEST_EVENT
FROM INTERACTIVE_JSON_DB.STREAMING.CUSTOMERS;

-- SHOW RESULTS OF THE INGESTION OF THE JSON WEB LOGS FROM OUR WEBSITE 
USE WAREHOUSE INTERACTIVE_WH_IOT;
ALTER WAREHOUSE INTERACTIVE_WH_IOT RESUME IF SUSPENDED;

SELECT 
    CASE 
        WHEN CLIENTIP LIKE '185.86.%' OR CLIENTIP LIKE '31.52.%' THEN 'London'
        WHEN CLIENTIP LIKE '81.105.%' OR CLIENTIP LIKE '82.132.%' THEN 'Manchester'
        WHEN CLIENTIP LIKE '92.233.%' OR CLIENTIP LIKE '86.149.%' THEN 'Birmingham'
        WHEN CLIENTIP LIKE '90.216.%' OR CLIENTIP LIKE '86.146.%' THEN 'Leeds'
        WHEN CLIENTIP LIKE '92.238.%' OR CLIENTIP LIKE '86.159.%' THEN 'Glasgow'
        WHEN CLIENTIP LIKE '81.100.%' OR CLIENTIP LIKE '86.147.%' THEN 'Liverpool'
        WHEN CLIENTIP LIKE '86.153.%' OR CLIENTIP LIKE '109.155.%' THEN 'Bristol'
        WHEN CLIENTIP LIKE '86.158.%' OR CLIENTIP LIKE '109.149.%' THEN 'Edinburgh'
        WHEN CLIENTIP LIKE '86.154.%' OR CLIENTIP LIKE '109.156.%' THEN 'Cardiff'
        WHEN CLIENTIP LIKE '86.160.%' OR CLIENTIP LIKE '109.150.%' THEN 'Belfast'
        ELSE 'Other UK'
    END AS CITY,
    COUNT(*) AS VISITORS,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS PERCENTAGE
FROM INTERACTIVE_JSON_DB.STREAMING.CUSTOMERS
GROUP BY 1
ORDER BY 2 DESC;

-- TOP 10 WEB PAGES
SELECT TITLE AS PAGE_TITLE, COUNT(*) AS PAGE_VIEWS
FROM INTERACTIVE_JSON_DB.STREAMING.CUSTOMERS
GROUP BY TITLE
ORDER BY 2 DESC
LIMIT 10;